#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

info()    { echo -e "${CYAN}${1}${RESET}"; }
success() { echo -e "${GREEN}${1}${RESET}"; }
warn()    { echo -e "${YELLOW}${1}${RESET}"; }
error()   { echo -e "${RED}${1}${RESET}"; }
bold()    { echo -e "${BOLD}${1}${RESET}"; }

bold "bt-autoswitch installer"
echo ""

if ! command -v pactl &>/dev/null; then
  error "ERROR: pactl not found. Install pulseaudio or pipewire-pulse and try again."
  exit 1
fi

info "Looking for Bluetooth audio card..."

CARDS=$(pactl list cards short | grep bluez | awk '{print $2}')
CARD_COUNT=$(echo "$CARDS" | grep -c . || true)

if [ "$CARD_COUNT" -eq 0 ]; then
  echo ""
  error "ERROR: No Bluetooth card found."
  warn "Make sure your headset is connected and try again."
  exit 1
elif [ "$CARD_COUNT" -gt 1 ]; then
  echo ""
  warn "Multiple Bluetooth cards found:"
  i=1
  while IFS= read -r card; do
    echo "  $i) $card"
    i=$((i + 1))
  done <<< "$CARDS"
  echo ""
  read -rp "Which one is your headset? (enter number): " CHOICE
  CARD=$(echo "$CARDS" | sed -n "${CHOICE}p")
else
  CARD="$CARDS"
fi

success "Using card: $CARD"
echo ""

info "Available profiles for $CARD:"
PROFILES=$(pactl list cards | awk "/Name: $CARD/,/^$/" | grep "Name:" | grep -v "^Name: $CARD" | awk '{print $2}')

if [ -z "$PROFILES" ]; then
  PROFILES=$(pactl list cards | awk "/bluez_card/,/^  Profiles:/{next} /^  Profiles:/,/^  Active Profile:/{print}" | grep -oP '(?<=Name: ).*')
fi

PROFILE_HQ=$(pactl list cards | awk "/Name: $CARD/,/^$/" | grep -i "a2dp" | head -1 | grep -oP '(?<=Name: ).*' || true)
PROFILE_MIC=$(pactl list cards | awk "/Name: $CARD/,/^$/" | grep -iE "headset_head_unit|handsfree_head_unit|hsp|hfp" | head -1 | grep -oP '(?<=Name: ).*' || true)

echo ""
echo "Fetching profiles..."
ALL_PROFILES=$(pactl list cards | grep -A 50 "Name: $CARD" | grep -E "^\s+\S+:$" | grep -v "Properties\|Ports\|Active" | sed 's/[: ]//g' || true)

PROFILE_LIST=$(pactl list cards | awk -v card="$CARD" '
  $0 ~ card {found=1}
  found && /Profiles:/ {inprofiles=1}
  found && inprofiles && /^\t\t[a-z]/ {print $1}
  found && inprofiles && /^[^\t]/ && !/Profiles:/ {inprofiles=0; found=0}
' | sed 's/://')

if [ -z "$PROFILE_HQ" ] || [ -z "$PROFILE_MIC" ]; then
  echo ""
  warn "Could not auto-detect profiles. Here are the available profiles:"
  pactl list cards | grep -A 80 "Name: $CARD" | grep -B1 "Available: yes" | grep -v "Available\|--" || \
    pactl list cards | grep -A 80 "Name: $CARD" | grep -E "^\s+(a2dp|headset|handsfree|off)" | awk '{print NR") "$1}'
  echo ""
  read -rp "Enter the HIGH QUALITY (A2DP) profile name: " PROFILE_HQ
  read -rp "Enter the MIC/HEADSET profile name: " PROFILE_MIC
fi

echo ""
info "  High quality profile: $PROFILE_HQ"
info "  Mic/headset profile:  $PROFILE_MIC"
echo ""
read -rp "Does this look right? [Y/n]: " CONFIRM
CONFIRM="${CONFIRM:-Y}"
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
  read -rp "Enter the HIGH QUALITY (A2DP) profile name: " PROFILE_HQ
  read -rp "Enter the MIC/HEADSET profile name: " PROFILE_MIC
fi

CONFIG_DIR="$HOME/.config/bt-autoswitch"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/config" <<EOF
# bt-autoswitch config — generated by install.sh
CARD="$CARD"
PROFILE_HQ="$PROFILE_HQ"
PROFILE_MIC="$PROFILE_MIC"
POLL_INTERVAL=2
EOF

echo ""
success "Config saved to $CONFIG_DIR/config"

mkdir -p "$HOME/.local/bin"
cp "$(dirname "$0")/bt-autoswitch.sh" "$HOME/.local/bin/bt-autoswitch"
chmod +x "$HOME/.local/bin/bt-autoswitch"
success "Script installed to ~/.local/bin/bt-autoswitch"

AUTOSTART_DIR="$HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"

cat > "$AUTOSTART_DIR/bt-autoswitch.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=bt-autoswitch
Comment=Auto-switch Bluetooth headset profile based on mic usage
Exec=/bin/bash $HOME/.local/bin/bt-autoswitch
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
EOF

success "Autostart entry created"

echo ""
bold "Installation complete!"
echo ""
info "bt-autoswitch will start automatically on your next login."
echo "To start it now, run:"
echo "  bt-autoswitch &"
echo ""
echo "To uninstall, run: bash uninstall.sh"